import type { AppLocale } from "../i18n";
import type { LobsterDebateChatPanelState } from "./lobsterDebatePanelTypes";

const STRINGS = {
  en: {
    title: "Loop Group Chat",
    subtitle: "Simulated group chat",
    debateSubtitle: "Red/Blue debate group chat",
    mainSubSubtitle: "Main/subtask group chat",
    executionRound: "Task execution chat",
    continueTask: "Continue",
    continueTaskTitle: "Ask the main task or judge to decide whether to continue",
    supplementTask: "Supplement Requirement",
    supplementTaskTitle: "Add follow-up requirements for the next Loop round",
    continuePromptDefault: "continue",
    supplementPromptDefault: "",
    supplementDialogTitle: "Supplement Loop requirements",
    supplementDialogDescription: "Add follow-up requirements. They will be recorded on this Loop task and shown to the main task or judge in the next round.",
    continueDialogTitle: "Continue Loop task",
    continueDialogDescription: "Confirm the message to send to the main task or judge. You can edit or add context before continuing.",
    continuePromptLabel: "Message",
    continuePromptRequired: "Enter a message before continuing.",
    supplementPromptLabel: "Requirement details",
    supplementPromptRequired: "Enter the supplemental requirements.",
    continueConfirm: "Confirm",
    continueCancel: "Cancel",
    stopTask: "Stop",
    stopTaskTitle: "Stop all running tasks for this Loop group chat",
    refresh: "Refresh",
    task: "Task",
    status: "Status",
    cli: "CLI",
    currentRound: "Current round",
    updatedAt: "Updated",
    participants: "Members",
    mainTask: "Main task",
    subtask: "Subtask",
    session: "Session",
    noSession: "No session",
    moderator: "Judge moderator",
    consensus: "Consensus",
    openDisagreements: "Open disagreements",
    noRounds: "No chat records yet.",
    noTranscript: "No transcript is available yet.",
    loadingError: "Unable to load transcript.",
    roundLabel: "Round {round}",
    debateRoundLabel: "Debate {round}",
    turnLabel: "Turn {turn}",
    finalStance: "Final stance",
    system: "System",
    transcriptClosed: "Closed",
    transcriptOpen: "In progress",
    stopped: "Stopped",
    startedAt: "Started",
    completedAt: "Completed",
    thinking: "{speaker} is thinking",
    finalStanceThinking: "{speaker} is preparing a final stance",
    consensusThinking: "Consensus summarizer is thinking",
    thinkingTag: "Thinking",
    scrollToBottomAria: "Jump to latest message",
  },
  "zh-CN": {
    title: "Loop 群聊",
    subtitle: "模拟群聊",
    debateSubtitle: "红蓝辩论群聊",
    mainSubSubtitle: "主从群聊",
    executionRound: "任务执行群聊",
    continueTask: "继续执行",
    continueTaskTitle: "让主任务或裁判主持人判断是否继续执行",
    supplementTask: "补充需求",
    supplementTaskTitle: "补充新的后续需求，供下一轮 Loop 任务读取",
    continuePromptDefault: "继续",
    supplementPromptDefault: "",
    supplementDialogTitle: "补充 Loop 需求",
    supplementDialogDescription: "补充新的后续需求。内容会写入当前 Loop 任务，并在下一轮提供给主任务或裁判主持人。",
    continueDialogTitle: "继续 Loop 任务",
    continueDialogDescription: "确认后会把这段内容发给主任务或裁判主持人继续判断，可先修改或补充说明。",
    continuePromptLabel: "消息内容",
    continuePromptRequired: "请输入继续消息。",
    supplementPromptLabel: "需求内容",
    supplementPromptRequired: "请输入补充需求。",
    continueConfirm: "确认",
    continueCancel: "取消",
    stopTask: "中止",
    stopTaskTitle: "中止这个 Loop 群聊关联的所有运行任务",
    refresh: "刷新",
    task: "任务",
    status: "状态",
    cli: "CLI",
    currentRound: "当前轮次",
    updatedAt: "更新时间",
    participants: "成员",
    mainTask: "主任务",
    subtask: "子任务",
    session: "会话",
    noSession: "无会话",
    moderator: "裁判主持人",
    consensus: "共识",
    openDisagreements: "未解决分歧",
    noRounds: "暂无群聊记录。",
    noTranscript: "当前暂无群聊 transcript。",
    loadingError: "无法读取群聊 transcript。",
    roundLabel: "第 {round} 轮",
    debateRoundLabel: "辩论 {round}",
    turnLabel: "第 {turn} 轮发言",
    finalStance: "最终立场",
    system: "系统",
    transcriptClosed: "已收束",
    transcriptOpen: "进行中",
    stopped: "已停止",
    startedAt: "开始",
    completedAt: "完成",
    thinking: "{speaker} 思考中",
    finalStanceThinking: "{speaker} 正在整理最终立场",
    consensusThinking: "共识汇总器思考中",
    thinkingTag: "思考中",
    scrollToBottomAria: "跳转到最新消息",
  },
} as const;

export type LobsterDebateChatPanelStrings = Record<keyof typeof STRINGS.en, string>;

export function getStrings(locale: AppLocale): LobsterDebateChatPanelStrings {
  return locale === "zh-CN" ? STRINGS["zh-CN"] : STRINGS.en;
}

export function buildLobsterDebateChatPanelTitle(
  state: LobsterDebateChatPanelState,
  strings: LobsterDebateChatPanelStrings,
): string {
  const taskId = state.task.id.trim();
  if (!taskId) {
    return strings.title;
  }
  const shortTaskId = taskId.length > 12 ? taskId.slice(0, 12) : taskId;
  return `${strings.title}: ${shortTaskId}`;
}
