import type { LoopDebateChatPanelState } from "./loopDebatePanelTypes";

const STRINGS = {
    title: "Loop 群聊",
    subtitle: "模拟群聊",
    debateSubtitle: "红蓝辩论群聊",
    mainSubSubtitle: "主从群聊",
    executionRound: "任务执行群聊",
    continueTask: "继续执行",
    continueTaskTitle: "让主任务或裁判主持人判断是否继续执行",
    supplementTask: "补充需求",
    supplementTaskTitle: "向当前 Loop 任务补充需求",
    askMainModel: "我要提问",
    askMainModelTitle: "向当前主模型所在会话提问",
    continuePromptDefault: "继续",
    supplementPromptDefault: "",
    supplementDialogTitle: "补充需求",
    supplementDialogDescription: "补充内容会显示在群聊中，并在下一轮提供给主任务或裁判主持人。这不会单独向主模型提问。",
    askDialogTitle: "向主模型提问",
    askDialogDescription: "这是当前任务和主模型的单独对话，只有气泡和输入框。回答时只显示等待动画，结束后给出最终答复，不展示思考过程。关闭后再打开会恢复这些气泡；如果还在回答，会继续显示等待动画。不会写成补充需求，也不会推动任务调度。",
    askChatEmpty: "还没有提问。在下方输入后发送。",
    askChatPlaceholder: "输入要问主模型的问题",
    askChatSend: "发送",
    askChatAbort: "中止",
    askChatWaiting: "正在回答",
    continueDialogTitle: "继续 Loop 任务",
    continueDialogDescription: "确认后会把这段内容发给主任务或裁判主持人继续判断，可先修改或补充说明。",
    continuePromptLabel: "消息内容",
    continuePromptRequired: "请输入继续消息。",
    continueModelChoiceLabel: "继续使用的运行配置",
    continueModelOriginal: "恢复原分组和配置",
    continueModelOriginalHint: "切回这个任务记录的 CLI 分组、配置档案、主/子模型和思考力度。",
    continueModelOriginalUnavailable: "这个任务没有记录启动时的分组、配置和模型，不能恢复原配置。",
    continueModelCurrent: "使用新配置的主子模型",
    continueModelCurrentHint: "使用当前 Loop 模式里配置的主模型和子模型继续。",
    continueModelSummary: "主模型 {main}，子模型 {subtask}",
    continueModelUnrecorded: "未记录",
    supplementPromptLabel: "需求内容",
    supplementPromptRequired: "请输入需求内容。",
    askPromptLabel: "问题",
    askPromptRequired: "请输入问题。",
    clarificationRequired: "请先填写{label}。",
    askAnswerTitle: "主模型回答",
    askAnswerWaiting: "主模型正在回答…",
    askAnswerReadyDescription: "以下是当前主模型会话的回答。",
    askAnswerErrorDescription: "主模型暂时没有完成回答。",
    askAnswerEmpty: "主模型没有返回可展示的回答。",
    askAnswerClose: "关闭",
    continueConfirm: "确认",
    continueCancel: "取消",
    stopTask: "中止",
    stopTaskTitle: "中止当前 Loop 任务",
    task: "任务",
    status: "状态",
    cli: "CLI",
    currentRound: "当前轮次",
    updatedAt: "更新时间",
    participants: "成员",
    mainTask: "主任务",
    subtask: "子任务",
    lastStarted: "最后启动",
    notStarted: "未启动",
    moderator: "裁判主持人",
    consensus: "共识",
    openDisagreements: "未解决分歧",
    noRounds: "暂无群聊记录。",
    noTranscript: "当前暂无群聊 transcript。",
    loadingError: "无法读取群聊 transcript。",
    roundLabel: "第 {round} 轮",
    debateRoundLabel: "辩论 {round}",
    turnLabel: "第 {turn} 轮发言",
    finalStance: "最终立场",
    user: "我",
    initialTaskPrompt: "任务发起",
    supplementalRequirement: "补充需求",
    system: "系统",
    transcriptClosed: "已收束",
    transcriptOpen: "进行中",
    stopped: "已停止",
    startedAt: "开始",
    completedAt: "完成",
    thinking: "{speaker} 思考中",
    finalStanceThinking: "{speaker} 正在整理最终立场",
    consensusThinking: "共识汇总器思考中",
    thinkingTag: "思考中",
    scrollToBottomAria: "跳转到最新消息",
    titleLoopPlus: "Loop+ 群聊",
    subtitleLoopPlus: "事件驱动逐项验收",
    loopPlusMode: "模式",
    loopPlusModeValue: "Loop+",
    loopPlusPhase: "阶段",
    loopPlusWake: "待唤醒",
    loopPlusWakeYes: "是",
    loopPlusWakeNo: "否",
    loopPlusCurrentCount: "当前项",
    loopPlusQueueCount: "排队项",
    loopPlusVisibleCount: "待验收总数",
    loopPlusRunningCount: "运行中",
    loopPlusPendingCount: "待启动",
    loopPlusReviewedCount: "验收结果",
    loopPlusActivityWaiting: "等待执行结束。主任务没有在生成。",
    loopPlusActivityReviewPending: "已有子任务排队等待验收，当前验收尚未开始。任务不能视为已完成。",
    loopPlusActivityReviewing: "正在验收 {subtask}。当前验收不表示其它执行已经结束。",
    loopPlusActivityStopped: "已停止。当前项和队列仍保留，但不会自动验收。",
    loopPlusActivityCompleted: "Loop+ 已全部收口。",
    loopPlusActivityIdle: "没有运行、待启动或待验收项。任务尚未标记完成。",
    loopPlusActivityPaused: "自动验收已暂停，需要继续后才会恢复。",
    loopPlusInvalid: "Loop+ 快照缺失或损坏（{reason}）。不能把该任务显示成空队列或已完成。",
    loopPlusStatusRunning: "运行中",
    loopPlusStatusPending: "待启动",
    loopPlusStatusReviewing: "正在验收",
    loopPlusStatusQueued: "待验收",
    loopPlusAcceptancePassed: "验收成功",
    loopPlusAcceptanceFailed: "验收失败",
    loopPlusStatusReviewPending: "待验收",
    loopPlusStatusWaiting: "等待中",
    loopPlusStatusStopped: "已停止",
    loopPlusStatusCompleted: "已收口",
    loopPlusStatusIdle: "空闲",
    loopPlusStatusPaused: "自动验收已暂停",
    loopPlusStatusInvalid: "快照不可用",
    loopPlusStatusExecutionCompleted: "执行结束，尚未验收",
    loopPlusStatusHeldReview: "验收已暂停",
    loopPlusStatusNotInSnapshot: "不在当前快照中",
    communicationFileOpen: "查看沟通文件",
    communicationFileDialogTitle: "沟通文件",
    communicationFileLoading: "正在读取沟通文件…",
    communicationFileMissing: "沟通文件不存在或已被删除。",
    communicationFileForbidden: "只能打开当前任务沟通目录中的 Markdown 文件。",
    communicationFileUnreadable: "无法读取该沟通文件。",
    communicationFileEmpty: "沟通文件是空的。",
    communicationFileTooLarge: "沟通文件过大，无法在弹窗中预览。",
    communicationFileClose: "关闭",
} as const;

export type LoopDebateChatPanelStrings = Record<keyof typeof STRINGS, string>;

export function getStrings(): LoopDebateChatPanelStrings {
  return STRINGS;
}
export function buildLoopDebateChatPanelTitle(
  state: LoopDebateChatPanelState,
  strings: LoopDebateChatPanelStrings,
): string {
  const title = state.loopPlus ? strings.titleLoopPlus : strings.title;
  const taskId = state.task.id.trim();
  if (!taskId) {
    return title;
  }
  const shortTaskId = taskId.length > 12 ? taskId.slice(0, 12) : taskId;
  return `${title}: ${shortTaskId}`;
}
