import { formatHomeDisplayPath } from "../shared/userHomePaths";

const SINITEK_RUNTIME_HINT = formatHomeDisplayPath(".sinitek_cli");

export const WEBVIEW_STRINGS = {
    appTitle: "携宁 CLI 助手",
    headerHelp: "使用说明",
    headerToolSettings: "工具设置",
    headerRules: "规则配置",
    headerNewSession: "新建会话",
    headerNewSessionConnectionCount: "当前长连接：{count}",
    headerResetSession: "重置当前会话",
    headerChatSearch: "搜索当前对话",
    chatSearchPlaceholder: "关键词",
    chatSearchPrev: "上一个匹配",
    chatSearchNext: "下一个匹配",
    chatSearchClose: "关闭搜索",
    chatSearchCountAria: "第 {current} 条，共 {total} 条",
    conversationTabsAria: "并行会话",
    conversationTabsPrevPage: "上一页会话",
    conversationTabsNextPage: "下一页会话",
    conversationTabLabel: "会话{index}",
    conversationTabCloseAria: "关闭{label}",
    emptyState: "输入需求，开始对话。",
    jsonTreeEmptyObject: "无属性",
    scrollToBottomAria: "跳转到最新消息",
    resultOnlyLabel: "仅看结果",
    resultOnlyAria: "仅显示用户消息和 AI 最终成功回复",
    queueIndicatorAria: "查看队列",
    queueIndicatorLabel: "队列",
    taskListTitle: "任务列表",
    cliSelectAria: "CLI 选择",
    configSelectAria: "配置选择",
    commonUnknownError: "未知错误",
    interactiveModeSelectAria: "交互回复模式",
    interactiveModeCoding: "Vibe",
    interactiveModeLoop: "Loop",
    interactiveModeGraph: "Graph",
    interactiveModeLoopPlus: "Loop+",
    interactiveModeLoopPlusHint: "单个子任务执行结束后立即验收，其它完成进入队列。",
    taskRoleMain: "Loop",
    taskRoleSubtask: "子任务",
    taskRoleSubtaskWithRound: "子任务·第{round}轮",
    sessionGraphLabel: "Graph",
    openLoopGroupChatAction: "打开 Loop 群聊",
    openLoopGroupChatActionTitle: "打开当前 Loop 任务的群聊页面",
    openGraphRunAction: "打开 Graph 运行图",
    openGraphRunActionTitle: "打开当前任务的 Graph 运行图面板",
    openCurrentLoopGroupChatLabel: "打开群聊",
    openCurrentLoopGroupChatAria: "打开当前 Loop 主任务群聊",
    openCurrentGraphRunLabel: "打开 Graph 图",
    openCurrentGraphRunAria: "打开当前 Graph 运行图面板",
    openConfigButton: "配置",
    promptPlaceholder:
      "Shift + Enter 换行，输入 @ 选择文件/目录；右键文件或目录，在菜单中单击“加入到 Sinitek CLI 引用”即可引用；支持附件黏贴...",
    commonCommandButton: "常用指令",
    pathPickerButton: "插入路径",
    attachmentButton: "上传附件",
    attachmentFallbackName: "文件",
    contextTagCurrentFile: "当前文件",
    contextTagSelection: "选中内容",
    contextTagSelectionWithRange: "当前文件: {file} [{range}]",
    contextTagRemoveAria: "移除上下文：{label}",
    thinkingModeAria: "思考模式",
    thinkingOptionOff: "off", 
    thinkingOptionLow: "low",
    thinkingOptionMedium: "medium",
    thinkingOptionHigh: "high",
    thinkingOptionXHigh: "xhigh",
    thinkingOptionMax: "max",
    thinkingOptionUltra: "ultra",
    openCodeThinkingOptionNone: "none",
    openCodeThinkingOptionMinimal: "minimal",
    openCodeThinkingOptionThinking: "thinking",
    openCodeThinkingUnavailable: "当前模型未声明可调 variants",
    openCodeThinkingMessageFollowDefault: "跟随此模型的 OpenCode 默认设置。",
    openCodeThinkingMessageLoading: "正在读取所选 OpenCode 模型声明的 variants。",
    openCodeThinkingMessageSelectModel: "请选择明确的 OpenCode provider/model 以查看可用 variants。",
    openCodeThinkingMessageMetadataError: "无法读取 OpenCode 模型元数据，将跟随 OpenCode 默认设置。",
    openCodeThinkingMessageNoVariants: "此模型未声明可调的 OpenCode variants。",
    openCodeThinkingMessageConfigVariants: "正在使用当前 OpenCode 配置声明的 variants。",
    openCodePrimaryModelSelectAria: "OpenCode 主模型选择",
    openCodeSmallModelSelectAria: "OpenCode 子模型选择",
    openCodePrimaryModelLabel: "主模型",
    openCodeSmallModelLabel: "子模型",
    codexLoopMainModelSelectAria: "Codex Loop/Graph 主模型选择",
    codexLoopSubtaskModelSelectAria: "Codex Loop/Graph 子模型选择",
    codexLoopMainThinkingModeAria: "Codex Loop/Graph 主模型思考模式",
    codexLoopSubtaskThinkingModeAria: "Codex Loop/Graph 子模型思考模式",
    codexLoopMainModelLabel: "主模型",
    codexLoopSubtaskModelLabel: "子模型",
    openCodePrimaryThinkingModeAria: "OpenCode 主模型思考模式",
    openCodeSmallThinkingModeAria: "OpenCode 子模型思考模式",
    openCodeNoConfiguredModel: "未配置模型",
    openCodeModelIssueInvalidJson: "当前 OpenCode 配置不是有效 JSON。",
    openCodeModelIssueMissingRoleModel: "配置中的模型值缺失。",
    openCodeModelIssueInvalidModelRef: "请使用精确的 OpenCode provider/model 引用。",
    openCodeModelIssueProviderNotFound: "配置的 provider 不存在。",
    openCodeModelIssueModelNotFound: "配置的模型未在对应 provider 中声明。",
    openCodeModelIssueDuplicateRoleModel: "主模型和子模型当前使用同一个配置模型。",
    openCodeModelIssueProviderDisabled: "配置的 provider 已禁用。",
    openCodeModelIssueModelFiltered: "配置的模型被 provider 设置排除。",
    openCodeModelIssueMetadataUnavailable: "无法读取 OpenCode 模型元数据。",
    openCodeModelIssueGeneric: "OpenCode 模型配置需要检查。",
    historyButton: "历史会话",
    sendButton: "发送",
    stopButton: "停止",
    scheduleTaskButton: "定时任务",
    scheduledTaskTitle: "定时执行 AI 任务",
    scheduledTaskClose: "关闭",
    scheduledTaskTimeLabel: "执行时间",
    scheduledTaskModeLabel: "执行模式",
    scheduledTaskModeAria: "定时任务执行模式",
    scheduledTaskPromptLabel: "提示词",
    scheduledTaskPromptPlaceholder: "输入稍后要执行的提示词...",
    scheduledTaskAttachmentsLabel: "附件",
    scheduledTaskSave: "添加",
    scheduledTaskManageTitle: "管理定时任务",
    scheduledTaskEmpty: "暂无定时任务。",
    scheduledTaskDelete: "删除",
    scheduledTaskStatusPending: "待执行",
    scheduledTaskStatusRunning: "执行中",
    scheduledTaskStatusCompleted: "已完成",
    scheduledTaskStatusFailed: "失败",
    scheduledTaskStatusCancelled: "已取消",
    scheduledTaskAttachmentCount: "附件：{count}",
    scheduledTaskTimeInvalid: "请选择未来的执行时间。",
    scheduledTaskPromptRequired: "请输入定时任务提示词。",
    scheduledTaskSaved: "定时任务已添加。",
    historyTitle: "历史记录",
    historyClearSessions: "重置当前会话",
    historyClearPrompts: "清空未收藏",
    historyClose: "关闭",
    historyTabsLabel: "历史记录",
    historyTabPrompts: "历史提示词",
    historyTabSessions: "历史会话",
    historySearchPlaceholder: "搜索提示词和会话",
    historySearchAriaLabel: "搜索提示词和会话",
    historyPromptFavoritesOnly: "仅收藏",
    historyPromptFavoriteSummary: "已收藏 {favorite}/{total}",
    historySessionViewLabel: "查看消息",
    historySessionExportLabel: "导出 TXT",
    historySessionExporting: "导出中...",
    historySessionMessagesTitle: "历史消息",
    historySessionMessagesClose: "关闭",
    historySessionMessagesLoading: "正在加载消息...",
    historySessionMessagesEmpty: "暂无保存的消息。",
    historySessionMessagesUnknown: "未知会话",
    historySessionMessagesMeta: "{cli} · {time}",
    historySessionMessageUser: "用户",
    historySessionMessageAssistant: "助手",
    historySessionMessageSystem: "系统",
    historySessionMessageTrace: "追踪",
    historySessionMessageThinking: "思考",
    historySessionMessageToolUse: "工具使用",
    rulesTitle: "规则",
    rulesClose: "关闭",
    rulesScopeLabel: "规则范围",
    rulesScopeGlobal: "全局规则",
    rulesScopeProject: "项目规则",
    rulesLoadCliAria: "加载 CLI",
    rulesLoadButton: "加载",
    rulesInputPlaceholder: "输入规则内容...",
    rulesSaveLabel: "保存覆盖到：",
    rulesSaveGroupLabel: "保存覆盖到",
    rulesSaveButton: "保存",
    toolSettingsTitle: "工具设置",
    toolSettingsClose: "关闭",
    toolSettingsGeneralTab: "常规配置",
    toolSettingsAiTaskTab: "AI任务配置",
    toolSettingsWorkspaceTab: "工作区",
    toolSettingsRepairTab: "自动修复",
    toolSettingsCliRepairHint: "列出扩展宿主当前无法启动的 CLI。一键修复会读取 Windows 当前的用户和系统 PATH，并把命令的绝对路径写入设置。",
    toolSettingsCliRepairSummaryHeader: "报错摘要",
    toolSettingsCliRepairActionHeader: "操作",
    toolSettingsCliRepairButton: "一键修复",
    toolSettingsCliRepairWorking: "修复中...",
    toolSettingsCliRepairEmpty: "当前没有可自动修复的问题。",
    toolSettingsCliRepairDetail: "扩展宿主找不到 {command}。终端里仍能运行，通常是因为 PATH 只在新终端或 shell profile 中生效。",
    toolSettingsHistoryRetentionDaysLabel: "历史保留天数",
    toolSettingsHistoryRetentionDaysTitle: "插件管理历史数据的全局保留期限",
    toolSettingsHistoryRetentionDaysHint: `适用于 ${SINITEK_RUNTIME_HINT} 下的日志、会话、提示词历史、任务记录和 Loop 记录。默认 30 天，可设置 1–3650 天。`,
    toolSettingsDebugLabel: "调试",
    toolSettingsDebugTitle: "调试日志",
    toolSettingsDebugToggle: "开启",
    toolSettingsAutoContextLabel: "自动文件标签",
    toolSettingsAutoContextTitle: "自动将当前文件/选区加入输入框上下文标签",
    toolSettingsAutoContextToggle: "开启",
    toolSettingsAutoCompactAfterRunLabel: "执行后自动压缩上下文",
    toolSettingsAutoCompactAfterRunTitle:
      "Codex、Claude、OpenCode 的全局设置。任务成功结束后自动压缩上下文。",
    toolSettingsAutoCompactAfterRunToggle: "开启",
    toolSettingsImplicitSubagentsLabel: "隐式子代理",
    toolSettingsImplicitSubagentsTitle:
      "Codex 和 OpenCode 隐式子代理能力的全局设置。",
    toolSettingsImplicitSubagentsToggle: "开启",
    toolSettingsImplicitSubagentsHint:
      "全局配置，默认关闭。关闭时，扩展会禁用 Codex multi_agent，并在本次 OpenCode 运行中拒绝 task 子代理。开启后，扩展保留各 CLI 自身可用的隐式子代理能力和 OpenCode task 权限。此设置不影响 Loop 编排。",
    toolSettingsHumanInteractionLabel: "人工交互",
    toolSettingsHumanInteractionTitle:
      "Codex、Claude 和 OpenCode 的全局设置。允许 Vibe 任务在继续执行前以结构化表单询问补充信息。",
    toolSettingsHumanInteractionToggle: "开启",
    toolSettingsHumanInteractionHint:
      "全局配置，默认开启。开启后，Codex 可使用 app-server/MCP 结构化请求；Codex、Claude 和 OpenCode Vibe 任务也可将明确澄清问题转为同一表单；拒绝表单会终止当前任务。",
    toolSettingsHumanInteractionTimeoutLabel: "人工交互超时（分钟）",
    toolSettingsHumanInteractionTimeoutTitle:
      "全局设置。Vibe 人工交互弹窗，以及 Loop、Loop+、Graph 主任务澄清表单，若在此时限内没有提交，则视为超时。AI 会自行选择最佳方案继续，不记为拒绝，也不进入待复核。默认 10 分钟，范围 1–240 分钟。",
    toolSettingsLoopMaxRoundsLabel: "Loop 最大轮次",
    toolSettingsLoopMaxRoundsTitle:
      "全局设置。新建 Loop 任务时允许的最大复核轮次。",
    toolSettingsLoopPlusDecisionSubtaskMaxLabel: "Loop+ 单次派发上限",
    toolSettingsLoopPlusDecisionSubtaskMaxTitle:
      "全局设置。限制 Loop+ 一次 dispatch 或 accept 最多附带的子任务数，默认 6，范围 1–20。不改变同时运行的并发上限。",
    toolSettingsLoopPlusMaxAcceptancesLabel: "Loop+ 最多验收次数",
    toolSettingsLoopPlusMaxAcceptancesTitle:
      "全局设置。限制一个 Loop+ 任务最多确认多少次子任务验收，默认 100，范围 1–999。达到上限后暂停自动验收和新派发，提高上限后可以继续。每个已确认的子任务 attempt 计 1 次。",
    toolSettingsLoopSubtaskMaxThinkingModeLabel: "Loop/Loop+ 子任务最大思考力度",
    toolSettingsLoopSubtaskMaxThinkingModeTitle:
      "全局设置。Loop/Loop+ 子任务使用此上限与所选模型思考力度中的较低值；max 和 ultra 最多为 xhigh。",
    toolSettingsLongTermMemoryLabel: "工作区 Harness 骨架",
    toolSettingsLongTermMemoryTitle:
      "工作区设置。提供仓库本地 AI 协作骨架，支持长期记忆、踩坑沉淀、任务交接、技能约定和 CodeGraph 辅助代码导航。",
    toolSettingsLongTermMemoryToggle: "开启",
    toolSettingsLongTermMemoryHint:
      "默认关闭。开启后可为当前工作区初始化 Harness，用于沉淀长周期上下文、复用代理工作规范、记录踩坑、交接任务并提升代码探索效率。",
    toolSettingsLongTermMemoryInstalledHint:
      "当前工作区已存在 .ch 目录，Harness 骨架已安装，无法在此关闭。",
    toolSettingsInstallCodeGraphLabel: "CodeGraph",
    toolSettingsInstallCodeGraphTitle:
      "工作区设置。只补齐缺失的 CodeGraph 步骤：需要时安装 CLI 并注册 MCP；CLI 和 MCP 已就绪时只初始化当前工作区索引。",
    toolSettingsInstallCodeGraphToggle: "开启",
    toolSettingsInstallCodeGraphHint:
      "默认关闭。开启后在可见终端只补齐缺失步骤：未安装 CLI 时执行完整安装、MCP 注册和索引初始化；CLI 与 MCP 已就绪但工作区未初始化时，只执行 codegraph init。",
    toolSettingsInstallCodeGraphInstallingHint:
      "正在终端中安装 CodeGraph。CLI、MCP 交互和工作区索引就绪后，此开关会自动勾选。",
    toolSettingsInstallCodeGraphInstalledHint:
      "当前工作区已存在 CodeGraph 索引，无法在此关闭。",
    toolSettingsMacShellLabel: "任务 Shell",
    toolSettingsMacShellAria: "macOS 任务 Shell",
    toolSettingsMacShellZsh: "zsh",
    toolSettingsMacShellBash: "bash",
    humanInteractionTitle: "人工交互",
    humanInteractionClose: "拒绝并关闭",
    humanInteractionDefaultInstruction:
      "AI 需要你补充以下信息后继续执行当前 Vibe 任务。",
    humanInteractionDefaultFieldLabel: "补充信息",
    humanInteractionDefaultFieldPlaceholder: "请输入补充信息...",
    humanInteractionSubmit: "提交",
    humanInteractionReject: "拒绝",
    humanInteractionRequired: "请填写“{label}”。",
    commonCommandsTitle: "常用指令",
    commonCommandsClose: "关闭",
    commonCommandCompactTitle: "压缩上下文",
    commonCommandCompactDesc: "适用于 Codex、Claude、OpenCode。压缩后下一个任务节省 token 数消耗",
    runConflictTitle: "任务执行中",
    runConflictClose: "关闭",
    runConflictBody: "检测到当前任务仍在执行，要如何处理这条消息？",
    runConflictDesc:
      "选择“加入队列”后，只有当前任务成功结束才会继续发送；如果当前任务失败或被停止，后续提示词会继续留在队列中。",
    runConflictQueueButton: "加入队列",
    runConflictPauseButton: "暂停并发送",
    queueTitle: "队列提示词",
    queueContinueLabel: "继续执行队列",
    queueCloseLabel: "关闭",
    queueEmpty: "当前没有待发送的提示词。",
    queueEditLabel: "编辑",
    queueSaveLabel: "保存",
    queueCancelEditLabel: "取消",
    queueEditPlaceholder: "发送前可在这里修改提示词...",
    queueMoveUpLabel: "上移",
    queueMoveDownLabel: "下移",
    queueRemoveLabel: "取消",
    runPromptViewAria: "查看当前会话提示词",
    runPromptViewLabel: "提示词",
    runStreamViewAria: "查看回放",
    runStreamViewLabel: "回放",
    runContextTokensAria: "已用上下文 {value}",
    runContextTokensLabel: "{value}",
    runContextTokensTitle: "当前上下文已用 {used} tokens",
    runContextTokensTitleWithWindow: "当前上下文已用 {used} / {window} tokens",
    runContextTokensPendingAria: "正在等待已用上下文",
    runContextTokensPendingTitle: "收到 Codex 上下文用量后显示",
    runPromptTitle: "会话提示词",
    runPromptClose: "关闭",
    runPromptEmpty: "当前会话暂无用户提示词。",
    runPromptLatestLabel: "最新",
    runStreamTitle: "回放",
    runStreamClose: "关闭",
    configApplyErrorTitle: "切换配置失败",
    configApplyErrorClose: "关闭",
    configApplyErrorCopy: "复制详情",
    runStreamExportLabel: "导出 JSONL",
    runStreamExportAria: "导出全部回放记录为 JSONL 文件",
    runStreamExporting: "导出中...",
    runStreamEmpty: "等待回放内容...",
    runStreamRecordIndex: "第 {index} 条",
    runStreamRecordEmpty: "（空消息）",
    runStreamTruncated: "已丢弃 {count} 条较早回放记录以限制内存占用。",
    runStreamRecordsShortened: "已缩短 {count} 条回放记录以限制内存占用。",
    runStreamRecordBytesTruncated: "该回放记录已丢弃前部 {count} 字节以限制内存占用。",
    runStreamSourceStdout: "标准输出",
    runStreamSourceStderr: "其它输出",
    runStreamSourceEvent: "事件",
    runStreamSlowLabel: "慢",
    runStreamVerySlowLabel: "极慢",
    runStatusCompacting: "压缩中",
    helpTitle: "使用说明",
    helpClose: "关闭",
    helpTabsLabel: "使用说明",
    helpTabModes: "模式说明",
    helpTabInstall: "安装",
    helpModesGeneralTitle: "如何选择",
    helpModesGeneralItem:
      "选择能安全完成任务的最轻模式：Vibe 做直接处理，Loop 按轮次协作，Loop+ 按事件验收，Graph 处理依赖复杂的流程。",
    helpModeVibeTitle: "Vibe",
    helpModeVibeBest: "适合：快速问答、读代码、小范围修改和探索性排查。",
    helpModeVibePros: "优点：交互直接、启动快、开销低。",
    helpModeLoopTitle: "Loop",
    helpModeLoopBest: "适合：中大型任务，需要拆分子任务并等一批执行结束后统一复核，也适合主从协作或红蓝辩论。",
    helpModeLoopPros: "优点：批次边界清楚、上下文共享、统一复核。",
    helpModeLoopPlusTitle: "Loop+",
    helpModeLoopPlusBest: "适合：子任务相对独立、希望完成后立即验收并持续推进的任务。",
    helpModeLoopPlusPros: "优点：完成即验收，多项可进入可见队列合并处理；支持追加消息或任务。主模型检查实现、契约、测试、产物、未授权改动及遗漏、回归和边界错误。需要时可以自行测试或启动应用，但不强制。最多验收次数可在“AI任务配置”中设置（默认 100，最大 999）。",
    helpModeGraphTitle: "Graph",
    helpModeGraphBest: "适合：复杂任务，需要明确依赖、并行执行和证据可视化。",
    helpModeGraphPros: "优点：依赖和进度直观，调度与恢复边界清楚。",
    helpInstallTitle: "安装",
    helpInstallWindowsPowerShellTitle: "Windows 先安装 PowerShell",
    helpInstallWindowsPowerShellNote: "Windows 必须先安装 PowerShell，再执行上面的命令。macOS 使用相同命令，不需要这一步。",
    helpInstallWindowsPowerShellWinget: "使用 winget 安装：",
    helpRemoveEnvTitle: "移除系统环境变量配置",
    helpRemoveEnvItem1:
      "使用该工具前需清理对 CLI 的系统级环境变量修改，避免与配置文件冲突。",
    helpRemoveEnvItemMac:
      "macOS：检查并移除 ~/.zprofile、~/.zshrc 或 ~/.bash_profile 中相关设置。",
    helpRemoveEnvItemWin:
      "Windows：通过“系统属性 > 高级 > 环境变量”删除为 CLI 手动添加的相关设置。",
    noConfigOption: "暂无配置",
    historyEmptySessions: "暂无会话历史",
    historyNoMatchingSessions: "没有匹配的历史会话。",
    historyEmptyPrompts: "暂无历史提示词",
    historyNoMatchingPrompts: "没有匹配的历史提示词。",
    historyEmptyFavoritePrompts: "暂无收藏提示词",
    sessionDefaultLabel: "未命名会话",
    sessionLoopLabel: "Loop",
    historySessionRoleMain: "☀️",
    historySessionRoleSubtask: "🌛",
    sessionOpenInTabsLabel: "已激活",
    sessionLoadLabel: "加载",
    sessionDeleteLabel: "删除",
    promptViewLabel: "查看",
    promptCollapseLabel: "收起",
    promptReuseLabel: "复用",
    promptFavoriteAddLabel: "收藏",
    promptFavoriteRemoveLabel: "取消收藏",
    promptEmptyLabel: "（空提示词）",
    traceToolFallback: "工具",
    traceToolReadFile: "读取文件",
    traceToolFindFiles: "查找文件",
    traceToolSearchText: "搜索文本",
    traceToolUpdateTaskList: "更新任务列表",
    traceToolFetchWebPage: "获取网页",
    traceToolWriteFile: "写入文件",
    traceToolEditFile: "编辑文件",
    traceToolRunTask: "执行任务",
    traceToolCreateTask: "创建任务",
    traceToolUpdateTask: "更新任务",
    traceToolTaskList: "任务列表",
    traceToolViewTask: "查看任务",
    traceToolStopTask: "停止任务",
    traceGitUpdate: "Git 更新",
    traceExec: "执行命令",
    traceExecTagTest: "测试",
    traceExecTagBuild: "构建",
    traceExecTagTypeCheck: "类型检查",
    traceExecTagLint: "代码检查",
    traceExecTagInstall: "安装",
    traceExecTagGitRead: "Git 查询",
    traceExecTagGitWrite: "Git 变更",
    traceExecTagSearch: "检索",
    traceExecTagFileRead: "读取",
    traceExecTagFileWrite: "写入",
    traceExecTagPython: "Python",
    traceExecTagRun: "运行",
    traceExecTagOther: "通用",
    traceFileUpdate: "文件变更",
    traceApplyPatch: "应用补丁",
    traceToolResult: "工具结果",
    traceWarning: "警告",
    traceError: "错误",
    traceThinking: "思考",
    traceWebSearch: "网络查询",
    traceInputLabel: "输入",
    traceOutputLabel: "输出",
    traceFileChangesLabel: "文件变更",
    traceExpandCommand: "展开查看完整命令",
    traceExpandChanges: "展开查看文件变更",
    traceExpandThinking: "展开查看思考详情",
    traceExpandTool: "展开查看工具详情",
    traceExpandToolResult: "展开查看 {tool} 输出",
    toastCopied: "已复制",
    toastCopyFailed: "复制失败",
    toastQueueAdded: "已加入队列",
    toastQueueUpdated: "队列提示词已更新",
    toastQueueEmptyPrompt: "提示词不能为空",
    toastQueueSendFailed: "队列发送失败，请先激活配置",
    toastConfigApplyPending: "配置切换中，请稍后再发送。",
    toastQueuePaused:
      "由于上一个任务未成功结束，队列已暂停。还有 {count} 条提示词留在队列中。",
    toastNoActiveConfig: "当前 CLI 未激活配置，请先在配置页激活后再发送。",
    toastFileReadFailed: "无法读取文件内容",
    toastReadFileFailed: "文件读取失败，请重试。",
    toastUploadTooManyFiles: "附件数量过多：已选择 {count} 个，最多 {max} 个。",
    toastUploadFileTooLarge: "附件“{name}”大小为 {size}，单文件最大 {max}。",
    toastRunStreamExportEmpty: "暂无可导出的回放记录。",
    toastRunStreamExportSuccess: "已导出到：{path}",
    toastRunStreamExportFailed: "导出回放记录失败：{error}",
    toastHistorySessionLoadFailed: "加载历史消息失败：{error}",
    toastHistorySessionExportEmpty: "暂无可导出的历史消息。",
    toastHistorySessionExportSuccess: "已导出到：{path}",
    toastHistorySessionExportFailed: "导出历史消息失败：{error}",
    toastConfigApplyErrorCopied: "已复制配置错误详情",
    rulesPathNoWorkspace: "路径：未检测到工作区",
    rulesPathPrefix: "路径：",
    rulesHintLoading: "正在加载...",
    rulesHintSaving: "正在保存...",
    rulesHintSelectCli: "请选择至少一个 CLI 进行覆盖保存。",
    rulesHintLoaded: "已加载 {scope}：{cli}。",
    rulesHintSaved: "{scope}已保存到：{targets}",
    thinkingOptionLabelLow: "low",
    thinkingOptionLabelOff: "off",
    thinkingOptionLabelMedium: "medium",
    thinkingOptionLabelHigh: "high",
    thinkingOptionLabelXHigh: "xhigh",
    thinkingOptionLabelMax: "max",
    thinkingOptionLabelUltra: "ultra",
    modelSelectAria: "模型选择",
    modelOptionDefault: "默认",
    loopExecutionModeSelectAria: "Loop 执行模式",
    loopExecutionModeOptionMainSubMultiAgent: "主从多智能体",
    loopExecutionModeOptionDebateMultiAgent: "红蓝辩论多智能体",
    modelOptionManage: "管理",
    modelAddPrompt: "输入模型名称：",
    modelAddTitle: "管理模型",
    modelAddLabel: "模型名称",
    modelAddPlaceholder: "输入模型名称，如 claude-sonnet-4-20250514",
    modelAddButton: "添加",
    modelSaveButton: "保存",
    modelAddEmptyError: "模型名称不能为空",
    modelAddExistsError: "模型已存在",
    modelManageEmpty: "暂无模型，请在下方添加。",
    modelManageCancelEdit: "取消编辑",
    modelManageEditing: "正在编辑：{model}",
    modelEditLabel: "编辑",
    modelMoveUpLabel: "上移",
    modelMoveDownLabel: "下移",
    modelRemoveLabel: "删除",
    modelDeleteConfirm: "确认删除模型“{model}”？",
} as const;

export type WebviewStringKey = keyof typeof WEBVIEW_STRINGS;

export function getWebviewStrings(): Record<WebviewStringKey, string> {
  return WEBVIEW_STRINGS;
}
